### PR TITLE
Pool capacity check

### PR DESCRIPTION
**Pull request by StewLG**
@fashberg @Cosmits:

I think this is working properly, but I'm going to wait a bit before merging it in case either of you has suggestions.

Let me know what you think.

### CODE REVIEW

**Comment by madtempest** [comment]
Hi @StewLG,

This looks like it works as expected. The only feedback I would have is the default -t zpool_capacity output.

In the README.md when there is no capacity check failures, the output reflects the status of ALL zpools available:

> OK - No Zpool capacity issues. ZPools examined: ApolloZpoolOne (75.8% used) ApolloZPoolEleven (64.0% used) Root level datasets examined: ApolloZpoolOne ApolloZPoolEleven

However if either of these pools happens to exceed the capacity value, the output will only reflect those pools that have capacity challenges:

> WARNING - Pool TankC usage 86.3% exceeds warning value of 80%- Pool TankB usage 82.5% exceeds warning value of 80%

Ideally the output would perhaps be 

> WARNING - Pool TankC usage 86.3% exceeds warning value of 80%- Pool TankB usage 82.5% exceeds warning value of 80% - Pool TankA (55% used)

Not a dealbreaker, but just some feedback. Otherwise, as mentioned, individual pool checks are returning with the expected data.

Thanks for the PR!

**Comment by StewLG** [comment]
I've made changes to implement your suggestion @madtempest, thank you. Have a look if you have time.

**Comment by madtempest** [comment]
Hi @StewLG thank you for the modification to have the default reflect all pools regardless of any having warnings!

Looks great.

**Comment by StewLG** [comment]
I hope we've found all the issues, but if anyone else has suggested changes, please take them up as an issue on Master. I'm sending this out and marking related issues closed.

**Pull request merged**
